# -*- coding: utf-8 -*-
"""Netflix_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrC-Fux2jltuxKODyHnVjQT0YprJ0QBh
"""

import os
os.environ['KAGGLE_USERNAME'] = 'netflix'
os.environ['KAGGLE_KEY'] = 'KGAT_9a962221b2ac769b0fb2fb3cfb6b185a'

!pip install kaggle

!kaggle datasets download -d 'gaddalaanjani/netfilx-dataset'

!ls /content

!pwd
!ls -l /content

!unzip /content/netfilx-dataset.zip -d /content/netflix

import pandas as pd
df = pd.read_csv("/content/netflix/imdb.csv")
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

print(df.columns)

print(df['year'])

df.drop('composer', axis=1, inplace=True)
print(df)

print(df['rating'].median())

df.isnull().sum()

df['year'].fillna(df['year'].mode()[0], inplace=True)

print(df['year'].head(10))
print(df['year'].isnull().sum())

for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

df.drop_duplicates(inplace=True)
print(df)

df['MovieAge'] = 2025 - df['year']
print(df[['year', 'MovieAge']].head())

print(df)

df.head()
df.info()

df.isnull().sum()

import matplotlib.pyplot as plt
plt.hist(df['year'], bins=10, color='skyblue', edgecolor='black')
plt.title('Distribution of Release Year')
plt.xlabel('Year')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
plt.boxplot(df['runtime'])
plt.title('Outlier Detection using Boxplot (Runtime)')
plt.ylabel('Runtime')
plt.show()

plt.scatter(df['year'], df['rating'], color='red')
plt.xlabel('Year')
plt.ylabel('Rating')
plt.title('Year vs Rating')
plt.show()

df = pd.get_dummies(df, columns=['language'], drop_first=True)

df.drop(['title', 'cast', 'director', 'writer'], axis=1, inplace=True)

X = df.drop('rating', axis=1)
y = df['rating']

import pandas as pd
X = df.drop('kind', axis=1)
y = df['kind']
X = pd.get_dummies(X, drop_first=True)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
print("Model Trained")
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)