# -*- coding: utf-8 -*-
"""social media preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heIgfuRPkucSjocAxPt-nUH5aU_wDJYx
"""

import os
os.environ['KAGGLE_USERNAME'] = 'socialmedia'
os.environ['KAGGLE_KEY'] = 'KGAT_9a962221b2ac769b0fb2fb3cfb6b185a'

!kaggle datasets download -d 'sharmajicoder/gen-z-social-media-usage-dataset'

!unzip /content/gen-z-social-media-usage-dataset.zip -d /content/social-media

import pandas as pd
df = pd.read_csv("/content/social-media/genz_social_media_usage_1M.csv")
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.describe()

df.duplicated().sum()

print(df.columns)

print(df['daily_usage_hours'])

df.isnull().sum()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

df.drop_duplicates(inplace=True)
print(df)

df['age_group'] = pd.cut(
    df['age'],
    bins=[0,18,25,35,100],
    labels=['Teen','Young Adult','Adult','Senior']
)

df['sleep_risk_score'] = (
    df['daily_usage_hours'] *
    df['screen_time_before_sleep']
)

print(df)

df.head()
df.info()

df.isnull().sum()

import matplotlib.pyplot as plt

plt.hist(df['daily_usage_hours'], bins=10, color='skyblue', edgecolor='black')
plt.title('Distribution of Daily Usage Hours')
plt.xlabel('Hours')
plt.ylabel('Frequency')
plt.show()

plt.boxplot(df['daily_usage_hours'])
plt.title('Outlier Detection using Boxplot (Daily Usage Hours)')
plt.ylabel('Hours')
plt.show()

plt.scatter(df['sleep_risk_score'], df['mental_health_score'])
plt.xlabel('Sleep Risk Score')
plt.ylabel('Mental Health Score')
plt.title('Sleep Risk Score vs Mental Health Score')
plt.show()

df = pd.get_dummies(df, columns=['gender'], drop_first=True)

df.drop(['country'], axis=1, inplace=True)

print(df)

df.isnull().sum()

import pandas as pd

X = df.drop('addiction_level', axis=1)
y = df['addiction_level']

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))