# -*- coding: utf-8 -*-
"""training_practice.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfN6czbwWBv7Q3GEeTTPh3I0dXImo4Yv
"""

# 1. find the length of integer
a=-12345
print(len(str(abs(a))))#abs is used to convert negative int to positive
# len funtion will not work in integer so str is used to covert int to string

# 2.PALINDROME
n=(input())
if n[::-1] == n:
  print("Palindrome")
else:
  print("Not a palindrome")

#3.LARGEST NUMBER
a=int(input())
b=int(input())
if(a>b):
  print(a,"is largest")
else:
  print(b ,"is largest")

# 4.FACTORIAL
n = int(input())
fact=1
for i in range (1,n+1):
  fact *= i
print(fact)

# 5.TYPECAST
a="10"
b=int(a)
print(type(a))
print(type(b))

# 6.AMSTRONG NUMBER
a = (input())
sum = 0
for i in a:
    n = int(i)
    sum = sum + n ** 3
if sum == int(a):
    print("Armstrong Number")
else:
    print("Not Armstrong Number")

# 7.PRIME NUMBER (1 TO 50)
for num in range(1, 51):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num)

# 8. Swap two variables without using third variable

a = 10
b = 20
a = a + b
b = a - b
a = a - b
print("a =", a)
print("b =", b)
print("_____________")


# WITHOUT MATHEMATICAL VARIABLE
a = 10
b = 20
a, b = b, a
print("a =", a)
print("b =", b)

# 9.Fibonacci Series
n = int(input())
a = 0
b = 1
for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

# 10.Average of 3 numbers
a,b,c=map(int,input().split())
avg=(a+b+c)/3
print(avg)

# 11.Celsius and fahrenhit convertion
c=int(input())
f=(c*(9/5))+32
print(f)

# 12. fahrenhit to celsius coversion
f=int(input())
c=(f-32)*(5/9)
print(c)

#13.find vowels of the string
s=input()
count=0
for ch in s:
  if ch in "aeiouAEIOU":
    print(ch)
    count+=1
print("count=",count)

#right triangle
row=int(input())
for i in range(1,row+1):
  for j in range (i):
    print("*",end=" ")
  print()

# 14.FIND GCD AND LCM
a=int(input())
b=int(input())
x=a
y=b
while b!=0:
  a,b=b,a%b
gcd=a
print(gcd)
lcm= (x*y)/gcd
print(lcm)

#15.largest and smallest number
num=list(map(int,input().split()))
print("largest=",max(num))
print("smallest=",min(num))

# 16.calculator of all operators
a=int(input())
op=input()
b=int(input())
if op=="+":
  print("Ans =",a+b)
elif op=="-":
  print("Ans =",a-b)
elif op=="*":
  print("Ans =",a*b)
elif op=="/":
  print("Ans =",a/b)
elif op=="%":
  print("Ans =",a%b)
elif op=="//":
  print("Ans =",a//b)
else:
  print("Inavlid operator")

# 17.Check if the number is positive negavive or Zero
n=int(input())
if n>0:
  print("Positive Number")
elif n<0:
  print("Negative Number")
else:
  print("Zero")

# 18.leap Year
year = int(input())
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print("Leap Year")
else:
    print("Not a Leap Year")

#19.ODD OR EVEN
n=int(input())
if n%2==0:
  print("Even")
else:
  print("Odd")

# 20.Anagram
s1 = input().lower()
s2 = input().lower()
if sorted(s1) == sorted(s2)
    print("Anagram")
else:
    print("Not Anagram")

#21.PRINT NUMBER IN RIGHT TRIANGLR
row =int(input())
for i in range(1,row+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#22.inverted right triangle
n=int(input())
for i in range(n):
  print(" " * i + "*" * (n-i))

#23.diamond pattern
n=4
for i in range (1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range (n-1,0,-1):
  print(" "*(n-i)+"* "*i)

#24.triangle

n=4
for i in range (1,n+1):
  print(" "*(n-i)+"* "*i)

#25.find largest of three number without if else
a, b, c = map(int, input().split())
print("Largest =", max(a, b, c))

#26.Anagram without sorted
s1 = input()
s2 = input()
if len(s1) == len(s2) and all(s1.count(i) == s2.count(i) for i in s1):
    print("Anagram")
else:
    print("Not Anagram")

# 27.Check whether a number is power of 2 without loop

n = int(input())
if n > 0 and (n & (n - 1)) == 0:
    print("Power of 2")

else:
    print("Not Power of 2")

# 28. check if two strig differ by exactly one character
s1 = input()
s2 = input()
count = 0
for i in range(len(s1)):
    if s1[i] != s2[i]:
        count += 1
if count == 1:
    print("Yes")
else:
    print("No")

# 29.print the largest substring without repeating character
s = input()
mlen = 0
for i in range(len(s)):
    sub = ""
    for j in range(i, len(s)):
        if s[j] not in sub:
            sub += s[j]
            mlen = max(mlen, len(sub))
        else:
            break
print(mlen)

#30.reverse and replace only the vowels from the string
r = input()
s =r.lower()
vowels = []
for ch in s:
    if ch in "aeiou":
        vowels.append(ch)
vowels.reverse()
result = ""
for ch in s:
    if ch in "aeiou":
        result += vowels.pop(0)
    else:
        result += ch
print(result)

#31.find the smallest positive missing number
n=int(input())
x=list(map(int,input().split()))
for i in range(1,n+1):
  d=x[i]
  if(x[i]==0):
    d=x[i-1]+1
    print(d)
    break

#32.finds the largest palindromic substring in a string.
s = input()
largest = ""
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1] and len(sub) > len(largest):
            largest = sub
print(largest)

#33.class and object
class student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("Name:",self.name)
    print("Age:",self.age)
obj=student("ROSHINI",3)
obj.display()

#34.inheritance
class Father:
  def bike(self):
    print("father has bike")
class Son(Father):
  def cycle(self):
    print("Son has Cycle")
obj=Son()
obj.bike()

#35.inheritance with pass statement
class Father:
  def property(self):
    print("Father property")
class Son(Father):
  pass
obj=Son()
obj.property()

#36.Simple progran using paa
for i in range(1,6):
  if i==3:
    pass
  print(i)

#37.Polymorphism(overriding)
class animal:
  def sound(self):
    print("Animal sound")
class dog(animal):
  def sound(self):
    print("Dog barks")
obj=dog()
obj.sound()

#38.abstraction
class Bank:
  def __init__(self):
    self.balance=5000
  def show_balance(self):
    print("Balance:",self.balance)
obj = Bank()
obj.show_balance()

#39.polymorphism (overloding)
class multiply:
  def product(self,a=None,b=None,c=None):
    if a and b and c:
      print("Product=",a*b*c)
    elif a and b:
      print("Product=",a*b)
    else:
      print("Invalid Input")
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

a=[[1,2],[3,4]]
b=[[1,2],[3,4]]

#40.check whether the number and its reverse is prime
n = int(input())
y = int(str(n)[::-1])
prime1 = True
prime2 = True
for i in range(2, n):
    if n % i == 0:
        prime1 = False
        break
for i in range(2, y):
    if y % i == 0:
        prime2 = False
        break
if prime1 and prime2 and n > 1 and y > 1:
    print("Both are prime")
else:
    print("Not prime")

#41.print even number as negative
x=int(input())
y=int(input())
for i in range(x,y):
    if i % 2 == 0:
        print(-i, end=" ")
    else:
        print(i, end=" ")

#42.Adam Number Reverse of (number²) = (reverse of number)²
x=int(input())
y=x**2
z=int(str(y)[::-1])
a=int(str(x)[::-1])
b=a**2
if b==z:
  print("Adam Number")
else:
  print("Not adam")

#43.circular prime
n = input()
prime = True
for i in range(len(n)):
    r = int(n[i:] + n[:i])
    for j in range(2, int(r**0.5) + 1):
        if r % j == 0:
            prime = False
            break
    if not prime:
        break
if prime:
    print("Circular Prime")
else:
    print("Not Circular Prime")

#44.duck number
n=input()
if '0' in n:
  print("duck number")
else:
  print("Not duck")

#45.Automorphic number
n=int(input())
d=n%10
sq=n**2
dsq=sq%10
if d==dsq:
  print("automorphic number")
else:
  print("non automorphic")

#46.PETERSON NUMBER
n=int(input())
x=str(n)
def factorial(n):
    fact=1
    for i in range(1,n+1):
        fact=fact*i
    return fact
sum=0
for j in range (len(x)):
    sum=sum+factorial(int(x[j]))
if n==sum:
    print("peterson")
else:
    print("no")

#spiral Matric

#Scenario based questions
#1. AI Message Recovery System
s = input()

for i in range(len(s)):
    t = s[:i] + s[i+1:]
    if t == t[::-1]:
        print("YES")
        break
else:
    print("NO")

n = int(input())
arr = list(map(int, input().split()))
total=n * (n+1) // 2
sum_arr = sum(arr)
missing_number = total - sum_arr
print(missing_number)

#3. Duplicate Product Detection Engine
a = input().split()
seen = []
for x in a:
    if x in seen:
        print("Duplicate Found")
        break
    seen.append(x)
else:
    print("No Duplicate")

#4. Trending Keyword Analyzer
a = input().split()
m = ""
for x in a:
    if a.count(x) > a.count(m) or (a.count(x) == a.count(m) and x < m):
        m = x
print(m)

#5. Banking Fraud Prevention System2
balance = int(input())
amount = int(input())

if balance - amount >= 1000:
    print("Transaction Approved")
else:
    print("Transaction Denied")

#Little Elephant and Strings
k, n = map(int, input().split())
favs = [input() for _ in range(k)]
for _ in range(n):
    s = input()
    print("Good" if len(s) >= 47 or any(f in s for f in favs) else "Bad")

#Rectangle and Square
a,b,c=map(int,input().split())
sq=c**2
rec=a*b
if sq==rec:
    print("yes")
else:
    print("no")

#Cake Discount
n=int(input())
if n>=5:
    price=n*85
else:
    price=n*100
print(price)
    
#Good Turn
t = int(input())
for _ in range(t):
    x, y = map(int, input().split())
    if x + y > 6:
        print("YES")
    else:
        print("NO")
